string(ASCII 27 Esc)
set(Verde "${Esc}[32m")
set(VerdeNegr "${Esc}[1;32m")
set(Branco "${Esc}[m")
set(VermNegr "${Esc}[1;31m")
set(AmareloNegr "${Esc}[1;33m")
set(CianoNegr "${Esc}[1;36m")

# Função para logging e debugging.
function(message)
  list(GET ARGV 0 MessageType)

  if(MessageType STREQUAL FATAL_ERROR OR MessageType STREQUAL SEND_ERROR)
    list(REMOVE_AT ARGV 0)
    _message(${MessageType} "${VermNegr}${ARGV}${Branco}")
  elseif(MessageType STREQUAL WARNING)
    list(REMOVE_AT ARGV 0)
    _message(STATUS "${AmareloNegr}${ARGV}${Branco}")
    list(REMOVE_AT ARGV 0)
    _message(STATUS "${CianoNegr}${ARGV}${Branco}")
  elseif(MessageType STREQUAL STATUS)
    list(REMOVE_AT ARGV 0)
    _message(STATUS "${Verde}${ARGV}${Branco}")
  elseif(MessageType STREQUAL STATUS_IMPORTANT)
    list(REMOVE_AT ARGV 0)
    _message(STATUS "${VerdeNegr}${ARGV}${Branco}")
  elseif(MessageType STREQUAL CONFIGURE_LOG)
  elseif(MessageType STREQUAL CHECK_START)
  elseif(MessageType STREQUAL CHECK_PASS)
  else()
    _message("${ARGV}")
  endif()
endfunction()



function(set_os Var WindowsValue LinuxValue)
  if("${CMAKE_SYSTEM_NAME}" STREQUAL "Windows" OR "${CMAKE_SYSTEM_NAME}" STREQUAL "MSYS")
    set(${Var} "${WindowsValue}" PARENT_SCOPE)
  elseif("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
    set(${Var} "${LinuxValue}" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "Este projeto não suporta o sistema \"${CMAKE_SYSTEM_NAME}\"")
  endif()
endfunction()
